import { db } from "@workspace/db";
import {
  usersTable,
  walletsTable,
  transactionsTable,
  verificationsTable,
  appsTable,
  contactsTable,
  notificationsTable,
} from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  await db.delete(notificationsTable);
  await db.delete(contactsTable);
  await db.delete(transactionsTable);
  await db.delete(verificationsTable);
  await db.delete(walletsTable);
  await db.delete(appsTable);
  await db.delete(usersTable);

  const [user] = await db
    .insert(usersTable)
    .values({
      id: "user_demo_001",
      username: "alex.world",
      displayName: "Alex",
      avatarUrl: null,
      worldId: "0x1a2b3c4d5e6f...",
      verificationLevel: "orb",
      walletAddress: "0x742d35Cc6634C0532925a3b8D8D82e3B3A8F9E0F",
      isVerified: true,
      country: "US",
      bio: "Verified human. Building the future.",
    })
    .returning();

  await db.insert(walletsTable).values({
    id: "wallet_001",
    userId: user.id,
    address: user.walletAddress,
    wldBalance: "487.25",
    usdcBalance: "1250.00",
    ethBalance: "0.3412",
    pendingGrants: 1,
    nextGrantDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
  });

  await db.insert(verificationsTable).values({
    id: "verif_001",
    userId: user.id,
    level: "orb",
    isVerified: true,
    verifiedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    nullifierHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
    expiresAt: new Date(Date.now() + 335 * 24 * 60 * 60 * 1000),
    canClaimGrant: true,
  });

  const now = Date.now();
  await db.insert(transactionsTable).values([
    {
      id: "tx_001",
      userId: user.id,
      type: "grant",
      status: "completed",
      amount: "10.00",
      amountUsd: "23.40",
      tokenSymbol: "WLD",
      fromAddress: null,
      toAddress: user.walletAddress,
      fromUsername: null,
      toUsername: "alex.world",
      txHash: "0xgrant001",
      note: "Monthly WLD grant",
      createdAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
    },
    {
      id: "tx_002",
      userId: user.id,
      type: "receive",
      status: "completed",
      amount: "25.00",
      amountUsd: "58.50",
      tokenSymbol: "WLD",
      fromAddress: "0xSender123",
      toAddress: user.walletAddress,
      fromUsername: "maria.world",
      toUsername: "alex.world",
      txHash: "0xreceive001",
      note: "Dinner split",
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: "tx_003",
      userId: user.id,
      type: "send",
      status: "completed",
      amount: "50.00",
      amountUsd: "117.00",
      tokenSymbol: "WLD",
      fromAddress: user.walletAddress,
      toAddress: "0xRecipient456",
      fromUsername: "alex.world",
      toUsername: "james.world",
      txHash: "0xsend001",
      note: "Concert tickets",
      createdAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: "tx_004",
      userId: user.id,
      type: "grant",
      status: "completed",
      amount: "10.00",
      amountUsd: "25.10",
      tokenSymbol: "WLD",
      fromAddress: null,
      toAddress: user.walletAddress,
      fromUsername: null,
      toUsername: "alex.world",
      txHash: "0xgrant002",
      note: "Monthly WLD grant",
      createdAt: new Date(now - 35 * 24 * 60 * 60 * 1000),
    },
    {
      id: "tx_005",
      userId: user.id,
      type: "swap",
      status: "completed",
      amount: "100.00",
      amountUsd: "100.00",
      tokenSymbol: "USDC",
      fromAddress: user.walletAddress,
      toAddress: user.walletAddress,
      fromUsername: "alex.world",
      toUsername: null,
      txHash: "0xswap001",
      note: "Swapped USDC to WLD",
      createdAt: new Date(now - 10 * 24 * 60 * 60 * 1000),
    },
  ]);

  await db.insert(appsTable).values([
    {
      id: "app_uniswap",
      name: "Uniswap",
      description: "The leading decentralized exchange. Swap tokens with verified humans.",
      iconUrl: null,
      category: "defi",
      url: "https://app.uniswap.org",
      isVerified: true,
      isFeatured: true,
      userCount: 1250000,
      rating: "4.8",
      requiresWorldId: false,
      tags: ["swap", "defi", "dex"],
    },
    {
      id: "app_gooddollar",
      name: "GoodDollar",
      description: "Universal Basic Income for verified humans. Claim your daily UBI.",
      iconUrl: null,
      category: "defi",
      url: "https://gooddollar.org",
      isVerified: true,
      isFeatured: true,
      userCount: 385000,
      rating: "4.5",
      requiresWorldId: true,
      tags: ["ubi", "defi", "social"],
    },
    {
      id: "app_lens",
      name: "Lens Protocol",
      description: "The social layer for Web3. Own your social graph.",
      iconUrl: null,
      category: "social",
      url: "https://lens.xyz",
      isVerified: true,
      isFeatured: true,
      userCount: 220000,
      rating: "4.6",
      requiresWorldId: false,
      tags: ["social", "decentralized", "profiles"],
    },
    {
      id: "app_worldchat",
      name: "World Chat",
      description: "Chat with verified humans only. No bots, no spam.",
      iconUrl: null,
      category: "social",
      url: "https://world.org/apps/chat",
      isVerified: true,
      isFeatured: true,
      userCount: 950000,
      rating: "4.7",
      requiresWorldId: true,
      tags: ["chat", "social", "verified"],
    },
    {
      id: "app_aave",
      name: "Aave",
      description: "Earn yield and borrow against your crypto assets.",
      iconUrl: null,
      category: "defi",
      url: "https://app.aave.com",
      isVerified: true,
      isFeatured: false,
      userCount: 890000,
      rating: "4.7",
      requiresWorldId: false,
      tags: ["lending", "yield", "defi"],
    },
    {
      id: "app_axie",
      name: "Axie Infinity",
      description: "Play-to-earn gaming with NFT creatures.",
      iconUrl: null,
      category: "gaming",
      url: "https://axieinfinity.com",
      isVerified: true,
      isFeatured: false,
      userCount: 1500000,
      rating: "4.3",
      requiresWorldId: false,
      tags: ["play-to-earn", "nft", "gaming"],
    },
    {
      id: "app_opensea",
      name: "OpenSea",
      description: "The largest NFT marketplace. Buy and sell digital collectibles.",
      iconUrl: null,
      category: "nft",
      url: "https://opensea.io",
      isVerified: true,
      isFeatured: false,
      userCount: 3200000,
      rating: "4.2",
      requiresWorldId: false,
      tags: ["nft", "marketplace", "collectibles"],
    },
    {
      id: "app_human_check",
      name: "HumanCheck",
      description: "Prove you're human to access gated content and services.",
      iconUrl: null,
      category: "utility",
      url: "https://humancheck.io",
      isVerified: true,
      isFeatured: false,
      userCount: 125000,
      rating: "4.9",
      requiresWorldId: true,
      tags: ["identity", "verification", "anti-bot"],
    },
    {
      id: "app_worldnews",
      name: "World News",
      description: "Human-curated news feed. Only verified human journalists.",
      iconUrl: null,
      category: "social",
      url: "https://world.org/apps/news",
      isVerified: true,
      isFeatured: false,
      userCount: 78000,
      rating: "4.4",
      requiresWorldId: true,
      tags: ["news", "social", "journalism"],
    },
    {
      id: "app_curve",
      name: "Curve Finance",
      description: "Stablecoin DEX with deep liquidity pools.",
      iconUrl: null,
      category: "defi",
      url: "https://curve.fi",
      isVerified: true,
      isFeatured: false,
      userCount: 450000,
      rating: "4.5",
      requiresWorldId: false,
      tags: ["stablecoin", "yield", "defi"],
    },
  ]);

  await db.insert(contactsTable).values([
    {
      id: "contact_001",
      userId: user.id,
      contactUsername: "maria.world",
      contactDisplayName: "Maria",
      contactAvatarUrl: null,
      contactWalletAddress: "0xMaria123456789",
      isVerified: true,
      verificationLevel: "orb",
      lastTransactionAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: "contact_002",
      userId: user.id,
      contactUsername: "james.world",
      contactDisplayName: "James",
      contactAvatarUrl: null,
      contactWalletAddress: "0xJames987654321",
      isVerified: true,
      verificationLevel: "orb",
      lastTransactionAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: "contact_003",
      userId: user.id,
      contactUsername: "sarah.eth",
      contactDisplayName: "Sarah",
      contactAvatarUrl: null,
      contactWalletAddress: "0xSarah555666777",
      isVerified: false,
      verificationLevel: "device",
      lastTransactionAt: null,
    },
  ]);

  await db.insert(notificationsTable).values([
    {
      id: "notif_001",
      userId: user.id,
      type: "grant",
      title: "WLD Grant Available",
      body: "Your monthly 10 WLD grant is ready to claim.",
      isRead: false,
      data: { amount: "10", tokenSymbol: "WLD" },
      createdAt: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      id: "notif_002",
      userId: user.id,
      type: "transaction",
      title: "Payment Received",
      body: "Maria sent you 25 WLD for dinner split.",
      isRead: false,
      data: { txId: "tx_002", amount: "25", tokenSymbol: "WLD" },
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: "notif_003",
      userId: user.id,
      type: "verification",
      title: "World ID Verified",
      body: "You have been successfully verified by the World Orb.",
      isRead: true,
      data: { level: "orb" },
      createdAt: new Date(now - 30 * 24 * 60 * 60 * 1000),
    },
    {
      id: "notif_004",
      userId: user.id,
      type: "app",
      title: "New App: World Chat",
      body: "World Chat is now available in the World ecosystem.",
      isRead: true,
      data: { appId: "app_worldchat" },
      createdAt: new Date(now - 15 * 24 * 60 * 60 * 1000),
    },
    {
      id: "notif_005",
      userId: user.id,
      type: "system",
      title: "Security Update",
      body: "Your World ID credentials have been updated with enhanced privacy protection.",
      isRead: false,
      data: null,
      createdAt: new Date(now - 12 * 60 * 60 * 1000),
    },
  ]);

  console.log("Seed complete!");
}

seed().catch(console.error);
